-#filename = 'untitleed.txt'
-#with open(filename) as f:
-#	content = f.readlines()
-#for line in content:
-#	print(line)
-import os.path
 
-filename = 'untitleed.txt'
-with open(filename) as filename:
-	content = filename.read()
-print(content)
